### ISSUE TITLE
Can't connect to db from sqlyog

### ISSUE THREAD

**Issue by yassersharaf** [khromov/php-wp-docker#1]
Hello,
I can't connect to db from an application like sqlyog please have a look at the settings

https://imgur.com/a/62Ywsyw

If these settings are wrong please correct me. (password is secret)

When I try to import a database from phpmyadmin I get: "#1227 - Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation"

**Comment by khromov** [comment]
Hey @yassersharaf !

#### Connecting from outside Docker

To connect from outside the Docker environment you need to forward the port - add the following to the `db` section in `docker-compose.yml`:

```
db:
    # ...
    ports:
      - "3306:3306"
```

Run `docker-compose up` again, you can now use SQLyog to connect to `127.0.0.1` on port `3306`.

However, this will probably not solve your import error, so please read on:

#### Regarding your issue with phpMyAdmin 

Your SQL dump likely contains a `CREATE DATABASE` statement and you are connecting as the `app` user. This user isn't allowed to create databases. 

Try removing any `CREATE DATABASE` statements from your SQL dump, make sure you select the `db` database in phpMyAdmin interface and import to it instead of on the top level (before you choose a database).

Hope that helps!

**Comment by yassersharaf** [comment]
Hello @khromov ,

Setting the port solved the connection problem, thank you. But I checked the sql file and it has no `create database` command but it logs this error: 

Error occured at:2020-12-07 13:28:51
Line no.:18
Error Code: 1227 - Access denied; you need (at least one of) the SUPER, SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation

The user `app` can't import or actually create tables that's the problem

**Comment by khromov** [comment]
@yassersharaf Try logging in as the MySQL root owner: `root / secret` and import it that way.

**Comment by yassersharaf** [comment]
@khromov Thank you so much. I don't have experience in docker but that solved my problem.
Regards
